name: flutter_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper: ^1.0.6
  charts_flutter: ^0.8.0
  device_info: ^0.4.0
  webview_flutter: ^0.3.14+1
  local_auth: ^0.6.0+1
  get_it: ^1.0.3+2
  shared_preferences: 0.5.3+4
  flutter_easyrefresh: ^2.0.4
  flutter_local_notifications: ^0.8.4
  azlistview: ^0.1.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  bottom_tab_bar:
    git: https://github.com/LiuC520/flutter_bottom_tab_bar.git

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/alan.jpg
  - images/scan.png
  - images/qianbao.png
  - images/licaitong.png
  - images/shoujichongzhi.png
  - images/xinyongka.png
  - images/shenghuojiaofei.png
  - images/you.png
  - images/chengshi.png
  - images/gongyi.png
  - images/baoxian.png
  - images/jiudian.png
  - images/didi.png
  - images/jingdong.png
  - images/meituan.png
  - images/maoyan.png
  - images/dazhongdianping.png
  - images/pdd.png
  - images/mogujie.png
  - images/elem.png
  - images/sanjiao.png
  - images/icon-up.png
  - images/youke.jpg
  - images/youke_head.png
  - images/ykblogo.png
  - images/wx_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
